version: '3'

services:
  express:
    build: .
    container_name: express
    # ports:
    #   - '3009:3009'
    depends_on:
      - mongodb
    environment:
      DATABASE_URL: ${DATABASE_URL}
      SECRET_KEY: ${SECRET_KEY}
    networks:
      - app
      - db
    command: ['/bin/sh', '-c', 'sleep 10 && npx prisma db push && npm start']
    restart: always

  mongodb:
    image: prismagraphql/mongo-single-replica:4.4.3-bionic
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      INIT_WAIT_SEC: 3
    # ports:
    #   - 27017:27017
    networks:
      - db
    restart: always

  react-app:
    build: ./react-client
    ports:
      - '${CLIENT_PORT}:80'
    environment:
      - NODE_ENV=production
    depends_on:
      - express
    networks:
      - app
    restart: always

volumes:
  data:

networks:
  app:
    driver: bridge
  db:
    driver: bridge
