version: '3'

services:
  express:
    build: .
    container_name: express
    ports:
      - '3000:3000'
    depends_on:
      - mongodb
    environment:
      DATABASE_URL: 'mongodb://admin:admin@mongodb:27017/mydatabase?authSource=admin&directConnection=true'
      SECRET_KEY: 'PasswordConnect-Hash'
    networks:
      - app
    command: ['/bin/sh', '-c', 'sleep 10 && prisma db push && npm start']
  mongodb:
    image: prismagraphql/mongo-single-replica:4.4.3-bionic
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      INIT_WAIT_SEC: 3
    ports:
      - 27017:27017
    networks:
      - app

  react-app:
    build: ./react-client
    ports:
      - '80:80'
    environment:
      - NODE_ENV=production
    depends_on:
      - express
    networks:
      - app
volumes:
  data:

networks:
  app:
    driver: bridge
