version: '3'

services:
  express-app:
    build: .
    ports:
      - '3000:3000'
    depends_on:
      - mongodb_container
      - react-app
    environment:
      DATABASE_URL: 'mongodb://admin:admin@localhost:27020/mydatabase?authSource=admin&directConnection=true'
      SECRET_KEY: 'PasswordConnect-Hash'
  mongodb_container:
    # This image automatically creates a replica set required for transactions
    image: prismagraphql/mongo-single-replica:4.4.3-bionic
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      INIT_WAIT_SEC: 3
    ports:
      - 27020:27017
  react-app: # React-приложение
    build: ./react-client # Путь к вашему React-приложению относительно корня вашего проекта
    ports:
      - '80:80' # Порт, на котором будет доступно ваше React-приложение
      - '8000:8000' # Порт, на котором будет доступно ваше React-приложение
volumes:
  react_app: # Объявление именованного тома
